---
name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.3.0

      - name: set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: "3.11"

      - name: install Poetry
        run: curl --silent --show-error --location https://install.python-poetry.org | python -

      - name: publish package
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
