---
name: release
on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    name: release to PyPI
    runs-on: ubuntu-latest
    steps:
      - name: set up Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.9"
      - name: publish package
        run: poetry publish --build
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
