---
name: test
on:
  - push
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.7"
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.3.0

      - name: set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Poetry
        run: curl --silent --show-error --location https://install.python-poetry.org | python -

      - name: install dependencies
        run: poetry install

      - name: run linters
        run: poetry run ./lint.sh

      - name: run tests
        run: poetry run python -m unittest discover --verbose
