---
name: test
on:
  - push
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.8"
          - "3.9"
          - "3.10"
          - "3.11"
    steps:
      - name: check-out repository
        uses: actions/checkout@v3.3.0

      - name: set up Python
        uses: actions/setup-python@v4.5.0
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Poetry
        run: curl --silent --show-error --location https://install.python-poetry.org | python -

      - name: install dependencies
        run: poetry install

      # Workaround for pytest failure when importing ansible-core 2.11
      # in importlib mode (AttributeError: '_AnsibleCollectionFinder' object
      # has no attribute 'find_spec').
      # See:
      # https://github.com/ansible/ansible-lint/issues/1919
      # https://github.com/pytest-dev/pytest/blob/1ae778f13ec8350e224ae6a365f21cc0d83af018/src/_pytest/pathlib.py#L496
      - name: run tests (Python 3.7)
        run: poetry run pytest --import-mode=prepend
        if: ${{ matrix.python-version == '3.7' }}

      - name: run tests (Python >= 3.8)
        run: poetry run pytest
        if: ${{ matrix.python-version != '3.7' }}
