---
name: test
on:
  - push
jobs:
  test:
    name: run tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.6"
          - "3.7"
          - "3.8"
          - "3.9"
    steps:
      - name: check-out repository
        uses: actions/checkout@v2.3.4

      - name: set up Python
        uses: actions/setup-python@v2.2.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Poetry
        run: python -m pip install --user poetry

      - name: install dependencies
        run: |
          cd "$GITHUB_WORKSPACE"
          poetry install

      - name: run linters
        run: |
          cd "$GITHUB_WORKSPACE"
          poetry run ./lint.sh

      - name: run tests
        run: |
          cd "$GITHUB_WORKSPACE"
          poetry run python -m unittest discover --verbose
